
logging:
  level:
    org: info
    com: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: 123456
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
